services:
  database:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: default
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8081"
    network_mode: "host"

  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www/html

